
#- name: Examine the swarm
  #no_log: true
#  shell: >
#        echo -e "GET /info HTTP/1.0\r\n" | nc -U /var/run/docker.sock | tail -n +6 | python -m json.tool
#  ignore_errors: yes
#  register: docker_swarm_result

#- set_fact:
#    docker_swarm_info: "{{ docker_swarm_result.stdout | from_json }}"
#- debug: var=docker_swarm_info.Swarm

- name: Get networks
  shell: >
        docker network ls --filter name={{ item }}$ | tail -n +2
  with_items:
     - <%= appName %>-net 
  register: network_result

- set_fact:
    docker_current_networks: "{{ network_result.results | map(attribute='stdout') | list | join(' ') }}"

- name: Create overlay networks
  shell: >
        docker network create -d overlay {{ item }}
  when: item not in docker_current_networks
  with_items:
     - <%= appName %>-net      

- name: Create overlay networks elk
  shell: >
        docker network create -d overlay elk-net
#  when: item not in docker_current_networks

- name: Start vizualizer only on managers
  run_once: true
  shell: >
       docker service create  \ 
       --name=viz \
       --label traefik.port=80 \
       --label traefik.frontend.rule=Host:viz.<%= appName %> \
       --publish=5050:8080/tcp \
       --constraint=node.role==manager \
       --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
       manomarks/visualizer
  tags:
        - viz          

- name: Start portainer on manager
  run_once: true
  shell: >
      docker service create \
      --label traefik.port=80 \
      --label traefik.frontend.rule=Host:portainer.<%= appName %> \
      --publish 9008:9000 \
      --name portainer \
      --constraint=node.role==manager \
      --mount "type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock" \
      portainer/portainer:1.11.3
