---
- hosts: all
  name: "** Mitosis Base **"
  gather_facts: false
  become: yes
  become_user: root
  vars:
    mitosis_home: /opt/mitosis
    docker_service: /usr/lib/systemd/system/docker.service
  pre_tasks:
   - name: 'Installing python2'
     raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  roles:
    - mitosis-common
    - mitosis-base

  
